name: Build & Publish vLLM Docker
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
concurrency:
  group: deployment
  cancel-in-progress: false
jobs:
  build-and-push:
    strategy:
      fail-fast: false
    runs-on: large_ubuntu_4cpu
    timeout-minutes: 360
    env:
      REGION: us-central1
      REPO: vllm
      IMAGE: vllm-forked
      STAGING_PROJECT: character-ai-staging
      PROD_PROJECT: character-ai
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: Determine tags
        id: tags
        run: |
          SHA=$(git rev-parse --short=7 HEAD)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "tags=${SHA},latest" >> $GITHUB_OUTPUT

      # Authenticate to staging and push
      - name: Authenticate to GCP Staging
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_STAGING }}
          service_account: ${{ secrets.GCP_SA_EMAIL_STAGING }}
          
      - name: "Set up Cloud SDK for Staging"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          install_components: "beta"
          
      - name: Configure Docker credential helper for Staging
        run: |
          gcloud --quiet auth configure-docker ${{ env.REGION }}-docker.pkg.dev
          
      - name: Build & Push to Staging
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile_internal
          platforms: linux/amd64
          push: true
          build-args: |
            HF_HOME=/huggingface/cache
          tags: |
            ${{ env.REGION }}-docker.pkg.dev/${{ env.STAGING_PROJECT }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ steps.tags.outputs.sha }}
            ${{ env.REGION }}-docker.pkg.dev/${{ env.STAGING_PROJECT }}/${{ env.REPO }}/${{ env.IMAGE }}:latest

      # Authenticate to prod and push
      - name: Authenticate to GCP Prod
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_PROD }}
          service_account: ${{ secrets.GCP_SA_EMAIL_PROD }}
          
      - name: "Set up Cloud SDK for Prod"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          install_components: "beta"
          
      - name: Configure Docker credential helper for Prod
        run: |
          gcloud --quiet auth configure-docker ${{ env.REGION }}-docker.pkg.dev
          gcloud --quiet auth configure-docker gcr.io
          
      - name: Build & Push to Prod and GCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile_internal
          platforms: linux/amd64
          push: true
          build-args: |
            HF_HOME=/huggingface/cache
          tags: |
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROD_PROJECT }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ steps.tags.outputs.sha }}
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROD_PROJECT }}/${{ env.REPO }}/${{ env.IMAGE }}:latest
            gcr.io/${{ env.PROD_PROJECT }}/vllm/${{ env.IMAGE }}:${{ steps.tags.outputs.sha }}
            gcr.io/${{ env.PROD_PROJECT }}/vllm/${{ env.IMAGE }}:latest
