name: Build & Publish vLLM Docker

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: deployment
  cancel-in-progress: false

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    timeout-minutes: 360

    env:
      REGION : us-central1
      REPO: vllm
      IMAGE: vllm-forked
      STAGING_PROJECT: character-ai-staging
      PROD_PROJECT: character-ai

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free up disk space
        run: |
          echo "Disk usage before cleanup:"
          df -h
          
          # Remove unnecessary packages and files
          sudo apt install aptitude -y >/dev/null 2>&1
          sudo aptitude purge aria2 ansible azure-cli shellcheck rpm xorriso zsync \
            esl-erlang firefox gfortran-8 gfortran-9 google-chrome-stable \
            imagemagick \
            libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl \
            mercurial apt-transport-https mono-complete libmysqlclient \
            unixodbc-dev yarn chrpath libssl-dev libxft-dev \
            libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
            snmp pollinate libpq-dev postgresql-client powershell ruby-full \
            sphinxsearch subversion mongodb-org azure-cli microsoft-edge-stable \
            -y -f >/dev/null 2>&1
          sudo aptitude purge microsoft-edge-stable -f -y >/dev/null 2>&1 || true
          sudo apt purge microsoft-edge-stable -f -y >/dev/null 2>&1 || true

          sudo apt-get remove -y '^aspnetcore-.*' '^dotnet-.*' '^llvm-.*' '^php.*' '^mysql-.*' '^postgresql-.*'
          sudo apt-get autoremove -y
          sudo apt-get autoclean
          
          # Remove large directories
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /usr/local/graalvm/
          sudo rm -rf /usr/local/.ghcup/
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/node_modules
          
          # Clean package caches
          sudo apt-get clean
          
          # Clean Docker
          sudo docker system prune -af --volumes
          sudo docker builder prune -af
          
          # Clean temp files
          sudo rm -rf /tmp/*
          sudo rm -rf /var/tmp/*
          
          echo "Disk usage after cleanup:"
          df -h
          
      - name: Check disk space
        run: |
          sudo dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -nr | head
          df . -h
          sudo du /usr/ -hx -d 4 --threshold=1G | sort -hr | head

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account:           ${{ secrets.GCP_SA_EMAIL }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          install_components: "beta"

      - name: Configure Docker credential helper
        run: |
          gcloud --quiet auth configure-docker ${{ env.REGION }}-docker.pkg.dev
          gcloud --quiet auth configure-docker gcr.io

      - name: Determine tags
        id: tags
        run: |
          SHA=$(git rev-parse --short=7 HEAD)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "tags=${SHA},latest" >> $GITHUB_OUTPUT

      - name: Build & Push to Staging, Prod, and GCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile_internal
          platforms: linux/amd64
          push: true
          no-cache: true
          build-args: |
            HF_HOME=/huggingface/cache
          tags: |
            ${{ env.REGION }}-docker.pkg.dev/${{ env.STAGING_PROJECT }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ steps.tags.outputs.sha }}
            ${{ env.REGION }}-docker.pkg.dev/${{ env.STAGING_PROJECT }}/${{ env.REPO }}/${{ env.IMAGE }}:latest
            ${{ env.REGION }}-docker.pkg.dev/${{ env.STAGING_PROJECT }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ steps.tags.outputs.sha }}
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROD_PROJECT }}/${{ env.REPO }}/${{ env.IMAGE }}:latest
            gcr.io/${{ env.PROD_PROJECT }}/vllm/${{ env.IMAGE }}:${{ steps.tags.outputs.sha }}
            gcr.io/${{ env.PROD_PROJECT }}/vllm/${{ env.IMAGE }}:latest

