name: Build & Publish vLLM Docker

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: deployment
  cancel-in-progress: false

jobs:
  build-and-push:
    runs-on: ubuntu-22.04-16core
    timeout-minutes: 360

    env:
      REGION : us-central1
      REPO: vllm
      IMAGE: vllm-forked
      STAGING_PROJECT: character-ai-staging
      PROD_PROJECT: character-ai

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free up disk space
        run: |
          echo "Disk usage before cleanup:"
          df -h
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get clean
          sudo docker system prune -af
          sudo docker volume prune -f
          echo "Disk usage after cleanup:"
          df -h

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account:           ${{ secrets.GCP_SA_EMAIL }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          install_components: "beta"

      - name: Configure Docker credential helper
        run: |
          gcloud --quiet auth configure-docker ${{ env.REGION }}-docker.pkg.dev
          gcloud --quiet auth configure-docker gcr.io

      - name: Determine tags
        id: tags
        run: |
          SHA=$(git rev-parse --short=7 HEAD)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "tags=${SHA},latest" >> $GITHUB_OUTPUT

      - name: Build & Push to Staging, Prod, and GCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile_internal
          platforms: linux/amd64
          push: true
          no-cache: true
          build-args: |
            HF_HOME=/huggingface/cache
          tags: |
            ${{ env.REGION }}-docker.pkg.dev/${{ env.STAGING_PROJECT }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ steps.tags.outputs.sha }}
            ${{ env.REGION }}-docker.pkg.dev/${{ env.STAGING_PROJECT }}/${{ env.REPO }}/${{ env.IMAGE }}:latest
            ${{ env.REGION }}-docker.pkg.dev/${{ env.STAGING_PROJECT }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ steps.tags.outputs.sha }}
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROD_PROJECT }}/${{ env.REPO }}/${{ env.IMAGE }}:latest
            gcr.io/${{ env.PROD_PROJECT }}/vllm/${{ env.IMAGE }}:${{ steps.tags.outputs.sha }}
            gcr.io/${{ env.PROD_PROJECT }}/vllm/${{ env.IMAGE }}:latest

